# BMAD-method template
meta:
  name: 培训计划/题库与台账模板
  version: 1.0.0
  owner: Compliance-Regulatory-Manager
  date: 2025-09-19
  standard: BMAD-method
  do_not_edit: false
inputs:
  - key: topics
    type: string[]
  - key: quiz
    type: csv
  - key: sessions
    type: csv
outputs:
  - key: training_pack
    type: pdf
quality_checks:
  - 签到/成绩/证书与到期提醒
