# BMAD-method template
meta:
  name: 培训计划与测验模板
  version: 1.0.0
  owner: Quality-Assurance-Manager
  date: 2025-09-19
  standard: BMAD-method
  do_not_edit: false
inputs:
  - key: topic
    type: string
  - key: content
    type: markdown
  - key: quiz
    type: csv
outputs:
  - key: training_pack
    type: pdf
quality_checks:
  - 题库/评分/纠偏建议
