# BMAD-method template
meta:
  name: 培训与胜任力矩阵模板
  version: 1.0.0
  owner: Clinical-Care-Manager
  date: 2025-09-19
  standard: BMAD-method
  do_not_edit: false
inputs:
  - key: skills
    type: string[]
  - key: staff
    type: csv
  - key: assess_rules
    type: object
outputs:
  - key: matrix
    type: csv
quality_checks:
  - 覆盖率≥95%，关键技能通过率≥98%
