version: 1
template_id: art-director/environment-spec
purpose: 场景设计规格
fields:
  scene: { type: string }
  scale: { type: string }
  composition: { type: list, items: string }
  materials: { type: list, items: string }
  palette_id: { type: string }
  lighting_notes: { type: list, items: string }
  modularity: { type: list, items: string, desc: "可生产性：模块化/复用点" }
outputs:
  - specs/environment-{{scene}}.yaml
