# <!-- Powered by BMAD™ Core -->
name: bmad-hospital-clinic-expansion-pack
version: 1.0.0
short-title: Hospital & Clinic Mgmt Pack
description: >-
  An expansion pack for BMAD-Method that standardizes a Hospital/Clinic Management Team:
  agents, tasks, output templates, checklists, roles, workflows and manifests aligned to BMAD core standards.
author: BMAD Team
slashPrefix: bmadHospital
links:
  repo: https://example.org/bmad-hospital
  docs: https://example.org/bmad-hospital/docs
tags: [Healthcare, Hospital, Clinic, BMAD]
compat:
  bmad-core: ">=1.10"
  runtimes: ["onprem", "cloud"]
i18n:
  defaultLocale: "zh-CN"
  locales: ["zh-CN", "en"]
license: MIT
