# <!-- Powered by BMAD™ Core -->
name: bmad-education-training-expansion-pack
version: 1.0.0
short-title: Education & Training Ops Pack
description: >-
  A BMAD-Method expansion pack for Education & Training management: agents, tasks,
  output templates, checklists, roles, workflows and manifests aligned to BMAD core standards.
author: BMAD Team
slashPrefix: bmadEdu
links:
  repo: https://example.org/bmad-education
  docs: https://example.org/bmad-education/docs
tags: [Education, Training, LMS, Assessment, Accessibility, FERPA, GDPR, xAPI, BMAD]
compat:
  bmad-core: ">=1.10"
  runtimes: ["cloud", "onprem"]
i18n:
  defaultLocale: "zh-CN"
  locales: ["zh-CN", "en"]
license: MIT
