version: 1
template_id: td/integration-pt-config
purpose: 生产跟踪系统集成配置
fields:
  endpoint: { type: string }
  mapping:
    type: table
    columns: [local_field, remote_field, notes]
  auth: { type: table, columns: [kind, key, notes] }
outputs:
  - integrations/pt-config.yaml
