version: 1
template_id: td/ocio-project-config
purpose: 项目 OCIO/ACES 配置
fields:
  ocio_config: { type: string, example: "aces_1.3/config.ocio" }
  displays: { type: list, items: string }
  views: { type: list, items: string }
  rules: { type: table, columns: [pattern, colorspace] }
outputs:
  - configs/ocio-config.yaml
