# <!-- Powered by BMAD™ Core -->
name: bmad-animation-expansion-pack
version: 1.0.0
short-title: Animation Production Pack
description: >-
  An expansion pack for BMAD-Method that standardizes an Animation Production Team:
  agents, tasks, output templates, checklists, roles, workflows and manifests aligned
  to BMAD core standards across creative preproduction → production → post & delivery.
author: BMAD Team
slashPrefix: bmadAnimation
links:
  repo: https://example.org/bmad-animation
  docs: https://example.org/bmad-animation/docs
tags: [Animation, Pipeline, BMAD]
compat:
  bmad-core: ">=1.10"
  runtimes: ["studio", "cloud"]
i18n:
  defaultLocale: "zh-CN"
  locales: ["zh-CN", "en"]
license: MIT
