# production-brief-tmpl.yaml
version: 1
template_id: exec-producer/production-brief
purpose: 项目创意/基调/范围的标准化梳理
fields:
  project_code: { type: string, required: true, example: ANIM-001 }
  title_cn: { type: string, required: true }
  title_en: { type: string, required: false }
  logline: { type: text, required: true, desc: "一句话概述" }
  tone_style: { type: list, items: string, example: ["科幻", "写实", "暖色"] }
  target_runtime_min: { type: integer, required: true }
  deliverables: { type: list, items: string, example: ["Teaser", "Trailer", "EP01"] }
  audience_rating: { type: string, enum: [G, PG, PG-13, R] }
  references: { type: list, items: url }
defaults:
  audience_rating: PG
outputs:
  - docs/production-brief-{{date}}.md
