# <!-- Powered by BMAD™ Core -->
name: bmad-venture-capital-expansion-pack
version: 1.0.0
short-title: Venture Capital Ops Pack
description: >-
  A BMAD-Method expansion pack for a Venture Capital management team: agents, tasks,
  output templates, checklists, roles, workflows and manifests aligned to BMAD core standards.
author: BMAD Team
slashPrefix: bmadVC
links:
  repo: https://example.org/bmad-vc
  docs: https://example.org/bmad-vc/docs
tags: [VentureCapital, FundOps, Compliance, ESG, CRM, KPI, BMAD]
compat:
  bmad-core: ">=1.10"
  runtimes: ["cloud", "onprem"]
i18n:
  defaultLocale: "zh-CN"
  locales: ["zh-CN", "en"]
license: MIT
