template:
  id: ise-external-stage-config-v1
  name: 外部 Stage 配置（S3/GCS/Azure）
  version: 1.0
  output:
    format: markdown
    filename: docs/external-stage-config.md
    title: "外部 Stage 配置"

sections:
  - id: locations
    title: 存储位置与命名（分区/层级）
  - id: credentials
    title: 凭证/密钥/网络策略（私连/策略）
  - id: retention
    title: 保留/生命周期与清理
  - id: security
    title: 加密/最小权限/审计
