template:
  id: ise-file-format-config-v1
  name: 文件格式配置（JSON/CSV/Parquet/Avro）
  version: 1.0
  output:
    format: markdown
    filename: docs/file-format-config.md
    title: "文件格式配置"

sections:
  - id: formats
    title: 格式参数与示例（压缩/编码）
  - id: schema_inference
    title: Schema 推断与变更
  - id: errors
    title: 错误处理与容错（ON_ERROR等）
