template:
  id: pc-training-v1
  name: 培训与意识提升
  version: 1.0
  output:
    format: markdown
    filename: docs/training-awareness.md
    title: "培训与意识"

sections:
  - id: audience
    title: 角色与课程大纲
  - id: cadence
    title: 周期/考核/记录
  - id: simulations
    title: 演练与钓鱼测试
