template:
  id: ml-training-plan-v1
  name: 训练计划（Snowpark/资源/产物）
  version: 1.0
  output:
    format: markdown
    filename: docs/training-plan.md
    title: "训练计划"

sections:
  - id: env
    title: 环境/依赖/镜像与资源
  - id: pipeline
    title: 数据→特征→训练→评估流水线
  - id: artifacts
    title: 产物（模型/指标/日志）
  - id: governance
    title: 审批/合规/配额
