analysis_pipeline:
  engine: "Fiji|CellProfiler|QuPath|Python"
  container: "Docker|Singularity"
  steps: ["illumination_correction", "segmentation", "feature_extraction", "stats"]
  version: "{{version}}"
  thresholds: { min_area: "{{px}}", min_signal: "{{au}}" }
  outputs: ["CSV", "OME-TIFF", "PDF"]
