culture_system:
  mode: "spinner|microfluidic|ALI|shaker"
  parameters:
    temperature: "{{temp}}"
    oxygen: "{{O2}}"
    pH: "{{pH}}"
    flow_rate: "{{flow}}"
  alarms: ["{{alarm}}"]
  restart_script: "{{script}}"
