imaging_settings:
  modality: "widefield|confocal|two-photon|light-sheet"
  channels:
    - name: "{{ch}}"
      ex_em: "{{ex}}/{{em}}"
      laser_power: "{{mW}}"
      exposure_ms: "{{exp}}"
      pinhole_AU: "{{pinhole}}"
  sampling: { pixel_size_nm: "{{px}}", z_step_um: "{{z}}", averaging: "{{avg}}" }
  live_cell: { temp: "{{temp}}", CO2: "{{co2}}", humidity: "{{humidity}}" }
