# <!-- Powered by BMAD™ Core -->
name: bmad-databricks-expansion-pack
version: 1.0.0
short-title: Databricks System Dev Pack
description: >-
  An expansion pack for BMAD-Method that standardizes Databricks Lakehouse
  system development with agents, tasks, output templates, checklists, roles,
  workflows and manifests aligned to BMAD core standards.
author: BMAD Team
slashPrefix: bmadDatabricks
links:
  repo: https://example.org/bmad-databricks
  docs: https://example.org/bmad-databricks/docs
tags: [Databricks, Lakehouse, BMAD]
compat:
  bmad-core: ">=1.10"
  runtimes: ["cloud"]
i18n:
  defaultLocale: "zh-CN"
  locales: ["zh-CN", "en"]
license: MIT
