# <!-- Powered by BMAD™ Core -->
name: bmad-architecture-design-expansion-pack
version: 1.0.0
short-title: Architecture Design Ops Pack
description: >-
  An expansion pack for BMAD-Method that standardizes an Architecture/Building Design
  management team with agents, tasks, output templates, checklists, roles, workflows
  and manifests aligned to BMAD core standards.
author: BMAD Team
slashPrefix: bmadArch
links:
  repo: https://example.org/bmad-architecture
  docs: https://example.org/bmad-architecture/docs
tags: [Architecture, AEC, BIM, LEED, CodeCompliance, QAQC, BMAD]
compat:
  bmad-core: ">=1.10"
  runtimes: ["cloud", "onprem"]
i18n:
  defaultLocale: "zh-CN"
  locales: ["zh-CN", "en"]
license: MIT
