meta: { name: "Breach Response Playbook", owner: compliance-legal }
stages:
  - detect: [triage, severity, notify_internal]
  - contain: [isolate, preserve_evidence]
  - eradicate: [fix, validate]
  - recover: [restore, monitor]
  - notify: [regulator, data_subjects, clients]
  - review: [rca, improvements]
