meta: { name: "Training Effectiveness Report", owner: hris-analytics }
sections:
  - { id: coverage, title: 覆盖与完成, fields: [assigned, completed, completion_rate] }
  - { id: outcomes, title: 成效, fields: [post_test_uplift, on_job_metrics, feedback] }
  - { id: actions, title: 改进行动, fields: [owner, due, status] }
