# <!-- Powered by BMAD™ Core -->
name: bmad-regbio-lab-expansion-pack
version: 1.0.0
short-title: RegBio Lab Management Pack
description: >-
  An expansion pack for BMAD-Method that standardizes a Regenerative Biology Lab
  (cell therapy/organoids/tissue engineering) management team with agents, tasks,
  output templates, checklists, roles, workflows and manifests aligned to BMAD core standards.
author: BMAD Team
slashPrefix: bmadRegBio
links:
  repo: https://example.org/bmad-regbio-lab
  docs: https://example.org/bmad-regbio-lab/docs
tags: [RegenerativeBiology, CellTherapy, Organoids, TissueEngineering, BMAD]
compat:
  bmad-core: ">=1.10"
  runtimes: ["onprem", "cloud"]
i18n:
  defaultLocale: "zh-CN"
  locales: ["zh-CN", "en"]
license: MIT
