# <!-- Powered by BMAD™ Core -->
name: bmad-venture-startup-expansion-pack
version: 1.0.0
short-title: Venture-backed Startup Ops Pack
description: >-
  A BMAD-Method expansion pack for venture-backed startup management: agents, tasks,
  output templates, checklists, roles, workflows and manifests aligned to BMAD core standards.
author: BMAD Team
slashPrefix: bmadVS
links:
  repo: https://example.org/bmad-venture-startup
  docs: https://example.org/bmad-venture-startup/docs
tags: [Startup, VentureBuilding, PMF, Growth, Fundraising, Compliance, KPI, BMAD]
compat:
  bmad-core: ">=1.10"
  runtimes: ["cloud", "onprem"]
i18n:
  defaultLocale: "zh-CN"
  locales: ["zh-CN", "en"]
license: MIT
