meta:
  name: 平台作战手册模板
  owner: Social-Influencer-Manager
  elicit: false
sections:
  - id: profile
    title: 受众与位置
    instruction: 平台受众与在漏斗位置的作用
  - id: content
    title: 内容规范
    instruction: 格式/时长/镜头/字幕/封面/禁用语
  - id: posting
    title: 发布时间与频率
    instruction: 建议时段与节奏
  - id: tagging
    title: 话题与标签
    instruction: 关键词/话题/品牌标签
  - id: metrics
    title: KPI 与告警
    instruction: 指标/阈值/异常处理
