template:
  id: api-spec-v1
  name: API Spec (OpenAPI)
  version: "1.0"
  output:
    format: yaml
    filename: docs/api/openapi.yaml
    title: OpenAPI Spec Skeleton
  sections:
    - id: info
      title: Info
      instruction: title/version/servers
    - id: security
      title: Security Schemes
      instruction: OIDC/API Key等
    - id: paths
      title: Paths
      instruction: 接口草案
    - id: components
      title: Components
      instruction: Schemas/Responses
