template:
  id: cookie-config-v1
  name: Cookie Consent Config
  version: "1.0"
  output:
    format: markdown
    filename: docs/cookie-config.md
    title: Cookie Consent Config
  sections:
    - id: categories
      title: Categories
      instruction: 必要/分析/广告/功能
    - id: controls
      title: Controls
      instruction: 拦截/同意/撤回/记录
    - id: regional
      title: Regional
      instruction: 地区差异/语言/可达性
