template:
  id: employer-brand-v1
  name: Employer Brand Playbook
  version: "1.0"
  output:
    format: markdown
    filename: docs/employer-brand.md
    title: Employer Brand Playbook
  sections:
    - id: evp
      title: EVP
      instruction: 雇主价值主张
    - id: content
      title: Content
      instruction: 主题/形式/节奏
    - id: channels
      title: Channels
      instruction: 校园/社媒/活动/员工倡导
