{
  "template":
    {
      "id": "product-vision-1p-v1",
      "name": "Product Vision One Pager",
      "version": "1.0",
      "output":
        {
          "format": "markdown",
          "filename": "docs/product-vision-1p.md",
          "title": "Product Vision One Pager",
        },
      "sections":
        [
          { "id": "vision", "title": "Vision Narrative", "instruction": "一句话愿景与三年图景" },
          { "id": "users", "title": "Key Users & JTBD", "instruction": "核心用户与JTBD" },
          { "id": "value", "title": "Value Proposition", "instruction": "价值主张与证据" },
          { "id": "metrics", "title": "North Star & Leading", "instruction": "北极星与领先指标" },
          { "id": "risks", "title": "Risks & Unknowns", "instruction": "关键风险与未知" },
        ],
    },
}
