meta:
  name: Enhanced Due Diligence Playbook
  owner: Compliance-AML-Officer
sections:
  - id: triggers
    title: 触发器
    elicit: true
    instruction: 高风险国/复杂结构/不一致/负面新闻/异常交易
  - id: actions
    title: 动作
    elicit: true
    instruction: 实地/第三方/银行信函/法律意见/董事会批准
