meta:
  name: CRM & Touchpoint Playbook
  owner: Investor-Relations-IR-Lead
sections:
  - id: hygiene
    title: 卫生与字段
    elicit: true
    instruction: 角色/兴趣/偏好/限制/合伙人匹配
  - id: play
    title: 节奏与剧本
    elicit: true
    instruction: 冷启/跟进/沉默唤醒/共投/转化
