# <!-- Powered by BMAD™ Core -->
name: bmad-scientific-research-expansion-pack
version: 1.0.0
short-title: Scientific Research Ops Pack
description: >-
  A BMAD-Method expansion pack that standardizes a Scientific Research Management Team with
  agents, tasks, output templates, checklists, roles, workflows and manifests aligned to BMAD core standards.
author: BMAD Team
slashPrefix: bmadResearch
links:
  repo: https://example.org/bmad-research
  docs: https://example.org/bmad-research/docs
tags: [Research, Lab, RCR, IRB, IACUC, DMP, Reproducibility, OpenScience, BMAD]
compat:
  bmad-core: ">=1.10"
  runtimes: ["cloud", "onprem"]
i18n:
  defaultLocale: "zh-CN"
  locales: ["zh-CN", "en"]
license: MIT
