# <!-- Powered by BMAD™ Core -->
name: bmad-snowflake-expansion-pack
version: 1.0.0
short-title: Snowflake System Dev Pack
description: >-
  An expansion pack for BMAD-Method that standardizes Snowflake (Data Cloud)
  system development with agents, tasks, output templates, checklists, roles,
  workflows and manifests aligned to BMAD core standards.
author: BMAD Team
slashPrefix: bmadSnowflake
links:
  repo: https://example.org/bmad-snowflake
  docs: https://example.org/bmad-snowflake/docs
tags: [Snowflake, DataCloud, BMAD]
compat:
  bmad-core: ">=1.10"
  runtimes: ["cloud"]
i18n:
  defaultLocale: "zh-CN"
  locales: ["zh-CN", "en"]
license: MIT
