# <!-- Powered by BMAD™ Core -->
name: bmad-staffing-hr-expansion-pack
version: 1.0.0
short-title: Staffing & HR Ops Pack
description: >-
  An expansion pack for BMAD-Method that standardizes a Talent Recruitment,
  Training, and Dispatch (Staffing) management team: agents, tasks, output templates,
  checklists, roles, workflows and manifests aligned to BMAD core standards.
author: BMAD Team
slashPrefix: bmadStaffingHR
links:
  repo: https://example.org/bmad-staffing-hr
  docs: https://example.org/bmad-staffing-hr/docs
tags: [Staffing, HR, Recruitment, Training, Dispatch, BMAD]
compat:
  bmad-core: ">=1.10"
  runtimes: ["cloud", "onprem"]
i18n:
  defaultLocale: "zh-CN"
  locales: ["zh-CN", "en"]
license: MIT
