template:
  id: application-ops
  title: 申请流程与材料
  sections:
    - id: checklist
      title: 材料清单
      type: table
      columns: [Item, Required, Format, Source, Validation]
      elicit: true
    - id: timeline
      title: 时间线与提醒
      type: table
      columns: [Stage, Deadline, Reminder, Owner, Exception]
      elicit: true
