meta: { name: Training & Attestation, version: 1.0 }
sections:
  - title: Role Matrix & Content
    instruction: "角色→课程/频次"
    elicit: true
  - title: Testing & Attestation
    instruction: "测验/通过线/电子签"
    elicit: true
  - title: Tracking & Reporting
    instruction: "完成率/迟滞/提醒"
    elicit: true
