meta: { name: Training Needs Assessment, version: 1.0 }
sections:
  - title: Roles & Risks
    instruction: "角色矩阵/法规/风险点"
    elicit: true
  - title: Gaps & Priorities
    instruction: "现状覆盖/差距/优先级"
    elicit: true
  - title: Accessibility
    instruction: "语言/无障碍/排班限制"
    elicit: true
