meta: { name: Training-related Incident RCA, version: 1.0 }
sections:
  - title: Timeline & Impact
    instruction: "事件/影响/时间线"
    elicit: true
  - title: Root Cause
    instruction: "5 Whys/系统/流程/人因"
    elicit: true
  - title: CAPA & Verification
    instruction: "措施/验证/防复发"
    elicit: true
