meta: { name: Training Audit Readiness, version: 1.0 }
sections:
  - title: Evidence Ledger
    instruction: "证据/抽样/可追溯"
    elicit: true
  - title: Scripts & Roles
    instruction: "问询脚本/分工/时限"
    elicit: true
  - title: Findings & CAPA
    instruction: "整改/验证/关闭"
    elicit: true
