meta:
  name: Training & Certification Plan
  output: docs/training/training-and-certification-plan.md
sections:
  - id: skills
    title: 能力画像
    elicit: true
    instruction: 角色/等级
  - id: courses
    title: 课程体系
    elicit: true
    instruction: 内外训
  - id: assessment
    title: 评估与认证
    elicit: true
    instruction: 考试/实操
  - id: refresh
    title: 复训与更新
    elicit: true
    instruction: 周期/要求
