# <!-- Powered by BMAD™ Core -->
name: bmad-travel-reception-expansion-pack
version: 1.0.0
short-title: Travel Reception Ops Pack
description: >-
  An expansion pack for BMAD-Method that standardizes a Travel Reception / Tour
  Operations management team: agents, tasks, output templates, checklists, roles,
  workflows and manifests aligned to BMAD core standards.
author: BMAD Team
slashPrefix: bmadTravel
links:
  repo: https://example.org/bmad-travel
  docs: https://example.org/bmad-travel/docs
tags: [Travel, TourOps, Hospitality, BMAD]
compat:
  bmad-core: ">=1.10"
  runtimes: ["cloud", "onprem"]
i18n:
  defaultLocale: "zh-CN"
  locales: ["zh-CN", "en"]
license: MIT
