meta:
  {
    name: Environment Lockfile,
    owner: Research-Software-Computing-Lead,
    output: docs/rs/environment-lock.md,
  }
sections:
  - { id: manager, title: 管理器与锁, instruction: Conda/Poetry/UV/renv 等, elicit: true }
  - { id: system, title: 系统与驱动, instruction: OS/内核/CUDA/cuDNN/编译器, elicit: true }
  - { id: hashes, title: 指纹与校验, instruction: 包/制品/数据哈希, elicit: true }
