meta:
  {
    name: lims-config-spec-tmpl.yaml,
    owner: Laboratory-Manager,
    output: docs/lab/lims-config-spec.md,
  }
sections:
  - { id: s1, title: 节1, elicit: true }
  - { id: s2, title: 节2, elicit: true }
