name: bmad-health-monitoring-expansion-pack
version: 1.0.0
short-title: Health Monitoring Ops Pack
description: Health Monitoring (RPM/IoMT) team pack aligned with BMAD standards.
author: BMAD Team
slashPrefix: bmadHealthMon
i18n: { defaultLocale: "zh-CN", locales: ["zh-CN", "en"] }
license: MIT
compat: { bmad-core: ">=1.10", runtimes: ["cloud", "onprem"] }
