version: 1
template_id: pipeline-td/launcher-config
purpose: Launcher/CLI 配置
fields:
  apps:
    type: table
    columns: [name, version, dcc, entrypoint, env_ref]
  env_ref: { type: path }
outputs:
  - launcher/cli-spec.yaml
