version: 1
template_id: pipeline-td/pt-connector-config
purpose: 生产跟踪连接器配置
fields:
  system: { type: string, enum: [ShotGrid, Ftrack] }
  mapping:
    type: table
    columns: [local_field, remote_field, notes]
outputs:
  - integrations/pt-connector-config.yaml
