version: 1
template_id: pipeline-td/validator-config
purpose: 验证配置（检查项/严重度/作用域/是否自动修复）
fields:
  checks:
    type: table
    columns: [id, description, severity, scope, autofix]
outputs:
  - validator/framework-spec.yaml
