# <!-- Powered by BMAD™ Core -->
name: bmad-suit-marketing-expansion-pack
version: 1.0.0
short-title: Suit Marketing Ops Pack
description: >-
  An expansion pack for BMAD-Method that standardizes a Suit/Tailoring Marketing
  (DTC/Retail/Omnichannel) management team with agents, tasks, output templates,
  checklists, roles, workflows and manifests aligned to BMAD core standards.
author: BMAD Team
slashPrefix: bmadSuitMkt
links:
  repo: https://example.org/bmad-suit-marketing
  docs: https://example.org/bmad-suit-marketing/docs
tags: [Apparel, Suit, Tailoring, Marketing, DTC, Retail, BMAD]
compat:
  bmad-core: ">=1.10"
  runtimes: ["cloud", "onprem"]
i18n:
  defaultLocale: "zh-CN"
  locales: ["zh-CN", "en"]
license: MIT
