version: 1
template_id: modeling-lead/bake-suite
purpose: 高低模烘焙与PBR输出配置
fields:
  maps:
    type: table
    columns: [name, res, bitdepth, colorspace, method]
  cage:
    type: table
    columns: [axis, offset, notes]
  matches:
    type: list
    items: string
outputs:
  - specs/bake-suite-{{asset}}.yaml
